stages:
  - unit-tests
  - build
  - deploy

unit-tests:
  stage: unit-tests
  script:
    - cd backend
    - npm install
    - node test.js

build:
  stage: build
  script:
    - docker compose build

deploy:
  stage: deploy
  script:
    - docker compose down
    - docker compose up -d --build