name: MERN CI Pipeline

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build


  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy containers
        run: |
          docker compose down
          docker compose up -d --build