name: Full CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:

  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------- FRONTEND ----------------
      - name: Build frontend image
        run: docker build -t alivfvf/mern-frontend:latest ./frontend

      - name: Push frontend image
        run: docker push alivfvf/mern-frontend:latest

      # ---------------- BACKEND ----------------
      - name: Build backend image
        run: docker build -t alivfvf/mern-backend:latest ./backend

      - name: Push backend image
        run: docker push alivfvf/mern-backend:latest


  deploy:
    runs-on: self-hosted
    needs: build-and-push

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------------- COPY DOCKER COMPOSE ----------------
      - name: Copy docker-compose to server
        run: |
          scp -o StrictHostKeyChecking=no \
          docker-compose.yml \
          ubuntu@${{ secrets.PROD_HOST }}:/home/ubuntu/docker-compose.yml \
          -i ${{ secrets.PROD_SSH_KEY }}

      # ---------------- COPY NGINX CONFIG ----------------
      - name: Copy nginx config to server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.PROD_HOST }} \
          "mkdir -p /home/ubuntu/nginx"

          scp -o StrictHostKeyChecking=no \
          nginx/nginx.conf \
          ubuntu@${{ secrets.PROD_HOST }}:/home/ubuntu/nginx/nginx.conf \
          -i ${{ secrets.PROD_SSH_KEY }}

      # ---------------- DEPLOY ----------------
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ubuntu
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |

            cd /home/ubuntu

            echo "Stopping old containers..."
            docker compose down || true

            echo "Pulling latest images..."
            docker pull alivfvf/mern-frontend:latest
            docker pull alivfvf/mern-backend:latest

            echo "Starting new stack..."
            docker compose up -d --remove-orphans

            echo "Deployment complete 🚀"